clear
addpath('../../matlab');
brs_parameters;

%% parameters which should be iterated

% parameters which should be varied for the evaluation
% #1: reproduction method
% #2: listener position
% #3: number of plane wave in pwd ('lwfs-sbl' only)
% #4: modal order in circular expansion ('lwfs-sbl' only)
% #5: fhigh of wfs-prefilter ('lwfs-sbl' only)

param_names = { 'method', ...
  'pos', ...
  'localsfs.sbl.Npw', ...
  'localsfs.sbl.order', ...
  'f' };

%% generate disired combinations of parameter values

param_values = {};

param_values = [param_values; allcombs( ...
  {'ref', 'wfs'}, ...
  {[0,0,0]}, ...
  {NaN}, ...
  {NaN}, ...
  {2000} ...
  )];

% 
param_values = [param_values; allcombs( ...
  {'lwfs-sbl'}, ...
  {[0,0,0]}, ...
  {1024, 64}, ...
  {27}, ...
  {2000} ...
  )];

% 
param_values = [param_values; allcombs( ...
  {'lwfs-sbl'}, ...
  {[-0.5,0.75,0]}, ...
  {1024}, ...
  {27, 11}, ...
  {2000} ...
  )];

param_values

%% Evaluation
% compute brs files
exhaustive_evaluation(@brs_driving_signals, param_names, param_values, ...
  conf, true);

% plot sound fields and store them in gnuplot-compatible files
exhaustive_evaluation(@eval_gnuplot_mono_soundfield, param_names, param_values, ...
  conf, false);
