function lwfs_sf_spectrum(conf)
% reads file generated by lwfw_ir*.m and appends the spectrum to a gnuplot
% readible txt file

%% ===== Computation =====================================================
load([conf.directory, evalGenerateFilename(conf), '.mat'], 'res');
  
if exist(conf.datafile, 'file')
  [f, P] = gp_load(conf.datafile);
else
  f = res.f;
  P = [];
end
P = [P, abs(res.P./res.P(1))];

gp_save( conf.datafile, [f, P] );

end